server {
    listen 80;
    server_name merchportal.customislandgifts.mt api.merchportal.customislandgifts.mt;

    location /.well-known/acme-challenge/ {
        root /var/www/merchportal-acme;
    }

    location / {
        return 404;
    }
}
